scenic_ideas_task:
  description: >
    Generate 50 scenic ideas for a Franz Kafka, Alexandre Dumas, or Thomas Hardy-style novel. 
    Focus on emotionally rich, visually compelling lonely landscapes that evoke psychological 
    depth and atmospheric isolation. Explore themes of moral conflict, psychological turmoil, love, and beauty.
  expected_output: >
    A numbered list of 50 scenic ideas, each with a brief but vivid description.
    Format: "1. [Scene Description]"
  agent: scenic_artist

prompt_generation_task:
  description: >
    Create detailed DALL-E prompts for each selected scenic idea.
    Each prompt should follow these guidelines:
    - 16:9 format painting
    - Impressionist oil painting style
    - Single dominant color palette
    - Minimal, broad brushstrokes
    - Natural elements that enhance the scene
    - No blank spaces or borders
    - Clear focal point tied to the scene's theme
  expected_output: >
    A series of detailed DALL-E prompts, one for each scenic idea.
    Each prompt should specify:
    1. The scene being depicted
    2. The dominant color palette
    3. The specific artistic style elements
    4. The focal point and composition
  agent: image_prompt_generator

generate_images_task:
  description: >
    Using DALL-E, generate painting-esque images for each scence based on the provided prompts.
    Check generated_images.md for existing images, if there is a similar image name then skip it and continue from the prompt where it left off - some prompts may have already been done!
    Save each image with its corresponding word as the filename.
  expected_output: >
    A list of generated image paths and their corresponding words.
  agent: image_generator
