scenic_ideas_task:
  description: >
    Generate 50 scenic ideas for a Dostoevsky-style novel.
    Each scene should be emotionally rich and visually compelling,
    capturing the psychological depth and atmospheric qualities typical of Dostoevsky's work.
    Consider themes of moral conflict, psychological turmoil, and social commentary.
  expected_output: >
    A numbered list of 50 scenic ideas, each with a brief but vivid description.
    Format: "1. [Scene Description]"
  agent: scenic_artist

prompt_generation_task:
  description: >
    Create detailed DALL-E prompts for each selected scenic idea.
    Each prompt should follow these guidelines:
    - 16:9 format painting
    - Impressionist oil painting style
    - Single dominant color palette
    - Minimal, broad brushstrokes
    - Natural elements that enhance the scene
    - No blank spaces or borders
    - Clear focal point tied to the scene's theme
  expected_output: >
    A series of detailed DALL-E prompts, one for each scenic idea.
    Each prompt should specify:
    1. The scene being depicted
    2. The dominant color palette
    3. The specific artistic style elements
    4. The focal point and composition
  agent: image_prompt_generator

image_generation_task:
  description: >
    Using DALL-E 3, generate images for each approved prompt while ensuring:
    - Strict adherence to 16:9 format (1792x1024)
    - Consistent impressionist oil painting style
    - Proper implementation of the single dominant color palette
    - Clear focal points as specified in the prompts
    - No blank spaces or borders
    - High-quality output with "standard" quality setting
  expected_output: >
    For each prompt, provide:
    1. The generated image URL
    2. Brief confirmation of successful generation
    3. Any relevant warnings or quality notes
  agent: dalle_artist 